# PANDAS DAY 1

###### 고수준의 자료구조와 파이썬에서 쉽고 빠르게 사용할 수 있는 데이터 분석 도구 포함
###### 넘파이, 사이파이, 스테이터스모델스, 사이킷런 맷플럿립 등과 함께 사용하는 경우가 많다
###### for 문을 사용하지 않고 데이터를 처리, 배열기반 함수를 제공하는 등 넘파이의 스타일을 많이 차용
###### 그러나 큰 차이점은 표 형식의 데이터나 다양한 형태의 데이터를 다루는 데 초첨을 맞춰 설계됨
###### 넘파이는 단일 산술배열 데이터를 다루는 데 특화

In [1]:
import pandas as pd

# 또는 from pandas Series.... 어쩌구로 해도 됨

###### 판다스의 자료구조는 Series, DataFrame, Index 3종이다. 각각 순서대로 1차원, 2차원, 색인 기능을 다루고 있다.

In [2]:
obj = pd.Series([4, 7, -5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

###### 인덱스와 요소를 순번대로 보여준다

In [4]:
type(obj)

pandas.core.series.Series

In [5]:
obj.values

array([ 4,  7, -5,  3], dtype=int64)

In [6]:
# 인덱스 빼고 데이터만 가져옴

In [7]:
obj.index # range(4)와 유사

RangeIndex(start=0, stop=4, step=1)

In [8]:
type(obj.index)

pandas.core.indexes.range.RangeIndex

In [9]:
# 판다스 안에 존재하는 레인지 인덱스란 뜻

In [10]:
type(obj.values)

numpy.ndarray

In [11]:
obj2 = pd.Series([4,7,-5,3], index = ['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [12]:
# 인덱스를 마음대로 지정할 수 있음

In [13]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [14]:
type(obj2.index)

pandas.core.indexes.base.Index

In [15]:
# 이건 레인지 인덱스는 아님

In [16]:
obj2.values

array([ 4,  7, -5,  3], dtype=int64)

In [17]:
type(obj2.values)

numpy.ndarray

In [18]:
# 넘파이 엔디어레이로 나옴

In [19]:
import numpy as np
a = np.array([1,2,3,4])
a[0]

1

In [20]:
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [21]:
obj[0]

4

In [22]:
obj2['d']

4

In [23]:
obj2['a']

-5

In [24]:
# 요런식으로 색인이 가능함

In [25]:
obj2['d'] = 6
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [26]:
# 색인하여 바꿀 수 있음

In [27]:
obj2[['c', 'a', 'd']]

c    3
a   -5
d    6
dtype: int64

In [28]:
obj2 > 0

d     True
b     True
a    False
c     True
dtype: bool

In [29]:
obj2[obj2>0]

d    6
b    7
c    3
dtype: int64

In [30]:
# 불리안값으로 색인 가능

In [31]:
obj2 * 2

d    12
b    14
a   -10
c     6
dtype: int64

In [32]:
np.exp(obj2)

d     403.428793
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

In [33]:
obj2

d    6
b    7
a   -5
c    3
dtype: int64

In [34]:
'b' in obj2 # 잘 안 될 경우에 뒤에 .index를 붙여도 됨

True

In [35]:
'e' in obj2

False

In [36]:
sdata = {'Ohio' : 35000, 'Texas' : 71000 ,'Oregon' : 16000, 'Utah' : 5000} # 딕셔너리르 준비했음

In [37]:
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [38]:
# 요런식으로 원하는 텍스트로 인덱싱 한 딕셔너리를 생성할 수 있음

In [39]:
stest = {'*' : 35000, '/' : 71000 ,'$' : 16000, '&' : 5000} # 특수문자 인덱싱 테스트
objtest = pd.Series(stest)
objtest

*    35000
/    71000
$    16000
&     5000
dtype: int64

In [40]:
# 특수문자의 경우 \ 와 같이 일부 안되는게 있지만, 일단은 텍스트로 인식해서 지정은 가능하다

In [42]:
# 인덱스로 사용할 리스트를 준비하자

states = ['California', 'Ohio', 'Oregon', 'Texas']
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [43]:
# 알아서 매핑해줌

In [44]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [45]:
# 널인것만 트루로 나옴

In [46]:
pd.notnull(obj4)

California    False
Ohio           True
Oregon         True
Texas          True
dtype: bool

In [47]:
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [48]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [49]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [50]:
# 연산이 불가능한 값은 NaN으로 출력됨

In [51]:
# 시리즈 자체에 이름 부여 가능

In [52]:
obj4.name = "population"
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [53]:
# name에 population이 들어감

###### 1.1 DataFrame

In [54]:
# 딕셔너리 준비

data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

# 키는 state, year, pop

frame = pd.DataFrame(data)
frame

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [55]:
# 시각적으로 깔끔하게 정리되어 나옴

In [56]:
frame.index

RangeIndex(start=0, stop=6, step=1)

In [57]:
# 키값이 df의 컬럼으로 매치됨

In [58]:
frame.columns

Index(['state', 'year', 'pop'], dtype='object')

In [59]:
frame.values

array([['Ohio', 2000, 1.5],
       ['Ohio', 2001, 1.7],
       ['Ohio', 2002, 3.6],
       ['Nevada', 2001, 2.4],
       ['Nevada', 2002, 2.9],
       ['Nevada', 2003, 3.2]], dtype=object)

In [61]:
type(frame.values)

numpy.ndarray

In [62]:
frame.head()

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [63]:
# 상위 5개 보여주는게 기본

In [64]:
frame.head(2)

state  year  pop
0  Ohio  2000  1.5
1  Ohio  2001  1.7

In [66]:
pd.DataFrame(data, columns = ['year', 'state','pop'])

year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [67]:
# 칼럼을 바꾸면 밸류값도 따라다님

In [68]:
pd.DataFrame(data, columns = ['year', 'state','pop', 'debt'])

year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [69]:
# value가 없는건 NaN으로 표기해줌

In [72]:
frame2 = pd.DataFrame(data, columns = ['year', 'state','pop', 'debt'],
                      index = ['one', 'two', 'three', 'four', 'five', 'six'])
frame2   

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [73]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [74]:
frame2.index

Index(['one', 'two', 'three', 'four', 'five', 'six'], dtype='object')

In [75]:
frame2['state']

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [76]:
type(frame2['state'])

pandas.core.series.Series

In [77]:
# 데이터프레임의 2차원을 색인하면 1차원이 나옴

In [78]:
frame2.state

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [80]:
# 같은 결과값이 나옴, state를 속성값 처럼 사용도 가능

In [81]:
frame2.year

one      2000
two      2001
three    2002
four     2001
five     2002
six      2003
Name: year, dtype: int64

In [82]:
# 여기 까지가 열 색인 방법임

In [83]:
frame2['one']

KeyError: 'one'

In [84]:
# 이렇게 행을 색인하는건 지원 안 됨

In [85]:
frame2.loc['one']

year     2000
state    Ohio
pop       1.5
debt      NaN
Name: one, dtype: object

In [86]:
# 이렇게 loc를 넣어줘야 행 색인이 가능함

In [87]:
# 역시 색인하면 2차원에서 1차원으로 감소했음

In [88]:
type(frame2.loc['one'])

pandas.core.series.Series

In [89]:
# Series네? 그럼 1차원이란 뜻임

In [90]:
frame2.loc['three']

year     2002
state    Ohio
pop       3.6
debt      NaN
Name: three, dtype: object

In [91]:
frame2

year   state  pop debt
one    2000    Ohio  1.5  NaN
two    2001    Ohio  1.7  NaN
three  2002    Ohio  3.6  NaN
four   2001  Nevada  2.4  NaN
five   2002  Nevada  2.9  NaN
six    2003  Nevada  3.2  NaN

In [92]:
# debt 열에 값 넣기

In [93]:
frame2['debt'] = 16.5
frame2

year   state  pop  debt
one    2000    Ohio  1.5  16.5
two    2001    Ohio  1.7  16.5
three  2002    Ohio  3.6  16.5
four   2001  Nevada  2.4  16.5
five   2002  Nevada  2.9  16.5
six    2003  Nevada  3.2  16.5

In [94]:
# 일괄적용됨

In [95]:
frame2['debt'] = np.arange(6.)
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [96]:
frame2['debt'] = np.arange(7.)
frame2

ValueError: Length of values (7) does not match length of index (6)

In [98]:
# 길이 갯수가 안 맞으면 문제 발생

In [99]:
val = pd.Series([-1.2, -1.5, -1.7], index = ['two', 'four', 'five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

In [100]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   0.0
two    2001    Ohio  1.7   1.0
three  2002    Ohio  3.6   2.0
four   2001  Nevada  2.4   3.0
five   2002  Nevada  2.9   4.0
six    2003  Nevada  3.2   5.0

In [101]:
# 이렇게 색인하면 1차원 Series 이므로 1차원값 지정 가능
frame2['debt'] = val
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [102]:
# two four five 인덱스에 해당하는 값만 넣어주고 나머지는 NaN 처리해줌

In [103]:
frame2['eastern'] = 0
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN        0
two    2001    Ohio  1.7  -1.2        0
three  2002    Ohio  3.6   NaN        0
four   2001  Nevada  2.4  -1.5        0
five   2002  Nevada  2.9  -1.7        0
six    2003  Nevada  3.2   NaN        0

In [104]:
frame2.state == 'Ohio'

one       True
two       True
three     True
four     False
five     False
six      False
Name: state, dtype: bool

In [105]:
frame2['eastern'] = frame2.state == 'Ohio'
frame2

year   state  pop  debt  eastern
one    2000    Ohio  1.5   NaN     True
two    2001    Ohio  1.7  -1.2     True
three  2002    Ohio  3.6   NaN     True
four   2001  Nevada  2.4  -1.5    False
five   2002  Nevada  2.9  -1.7    False
six    2003  Nevada  3.2   NaN    False

In [106]:
del frame2['eastern']
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [107]:
# 열삭제

In [108]:
pop = {'Nevada': {2001: 2.4, 2002: 2.9},
       'Ohio': {2000: 1.5, 2001: 1.7, 2002: 3.6}}

# 딕셔너리의 밸류값이 딕셔너리인 구조임

# 네바다와 오하이오가 최상위에 있는 키 이므로 컬럼이 됨

frame3 = pd.DataFrame(pop)
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [109]:
# 딕셔너리 내부 딕셔너리의 키값은 인덱스로 갔음

In [110]:
frame3.T

2001  2002  2000
Nevada   2.4   2.9   NaN
Ohio     1.7   3.6   1.5

In [111]:
pd.DataFrame(pop, index = [2001, 2002, 2003])

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2003     NaN   NaN

In [112]:
# 지정하지 않은건 사라지고, 추가된건 value를 NaN 처리하고 새로 생성해줌

In [113]:
frame3['Ohio'][:2] # 또는 [:-1]

2001    1.7
2002    3.6
Name: Ohio, dtype: float64

In [115]:
pdata = {'Ohio' : frame3['Ohio'][:-1],
        'Nevada' : frame3['Nevada'][:2]}

pd.DataFrame(pdata)

Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9

In [116]:
frame3.name = "POPULATION"
frame3

Nevada  Ohio
2001     2.4   1.7
2002     2.9   3.6
2000     NaN   1.5

In [118]:
frame3.index.name = 'year'
frame3.columns.name = 'state'
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [120]:
frame3.values

array([[2.4, 1.7],
       [2.9, 3.6],
       [nan, 1.5]])

In [121]:
frame3.values.dtype

dtype('float64')

In [122]:
frame2

year   state  pop  debt
one    2000    Ohio  1.5   NaN
two    2001    Ohio  1.7  -1.2
three  2002    Ohio  3.6   NaN
four   2001  Nevada  2.4  -1.5
five   2002  Nevada  2.9  -1.7
six    2003  Nevada  3.2   NaN

In [123]:
frame2.values

array([[2000, 'Ohio', 1.5, nan],
       [2001, 'Ohio', 1.7, -1.2],
       [2002, 'Ohio', 3.6, nan],
       [2001, 'Nevada', 2.4, -1.5],
       [2002, 'Nevada', 2.9, -1.7],
       [2003, 'Nevada', 3.2, nan]], dtype=object)

In [124]:
frame2.columns.dtype

dtype('O')

In [125]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [126]:
# 이 끝에 오브젝트의 O 가 위에서 나온거임

### 3. Index

In [127]:
pd.Series(range(3))

0    0
1    1
2    2
dtype: int64

In [128]:
obj = pd.Series(range(3), index = ['a','b','c'])

In [138]:
Index = obj.index

In [139]:
Index

Index(['a', 'b', 'c'], dtype='object')

In [140]:
# 이걸 또 색인할 수 있음

Index[1:]

Index(['b', 'c'], dtype='object')

In [141]:
# 인덱스는 원래 메타정보라 색인이 불가능한데 가능하게 해줌

In [142]:
Index[1] = 'd'

TypeError: Index does not support mutable operations

In [136]:
# 이건 안됨

In [143]:
labels = pd.Index(np.arange(3))
labels

Int64Index([0, 1, 2], dtype='int64')

In [144]:
obj2 = pd.Series([1.5,-2.5,0], index=labels)
obj2

0    1.5
1   -2.5
2    0.0
dtype: float64

In [145]:
obj2.index is labels

True

In [146]:
# obj2의 인덱스가 labels 인가 물어본거임

In [147]:
frame3

state  Nevada  Ohio
year               
2001      2.4   1.7
2002      2.9   3.6
2000      NaN   1.5

In [148]:
frame3.columns

Index(['Nevada', 'Ohio'], dtype='object', name='state')

In [149]:
'Ohio' in frame3.columns

True

In [150]:
2003 in frame3.index

False

In [151]:
pd.Index(['foo', 'foo', 'bar', 'bar']) # 여기서 인덱스는 대문자를 쓴 변수임

Index(['foo', 'foo', 'bar', 'bar'], dtype='object')

### 실습

###### 1. 딕셔너리를 시리즈로 변환하기

In [ ]:
dic_data = {'a';1,'b';2,'c':3} # index, values 출력

###### 2. 리스트를 시리즈로 변환하기

In [ ]:
list_data = ['2019-01-02', 3.14, 'ABC', 100, True] # index, values 출력

###### 3. 튜플을 시리즈로 변환하기

In [ ]:
tup_data = ('영인', '2010-05-01', '여', True) # index, values 출력

###### 4. 튜플을 시리즈로 변환하기 (index 설정하기)

In [ ]:
tup_data = ('영인', '2010-05-01', '여', True)
Index_name = ['이름', '생년월일', '성별', '학생여부']

###### 5. 시리즈 원소 선택

In [ ]:
tup_data = ('영인', '2010-05-01', '여', True)
Index_name = ['이름', '생년월일', '성별', '학생여부']

In [ ]:
# 색인으로 '영인'값 얻어오기

In [ ]:
# 색인으로 '생년월일'과 '성별' 얻어오기

###### 6. 딕셔너리를 데이터 프레임으로 변환

In [ ]:
dict_data = {'c0':[1,2,3], 'c1':[4,5,6], 'c2':[7,8,9],'c3':[10,11,12], 'c4':[13,14,15]}

### 정답모음

dict_data = {'a' : 1, 'b' : 2, 'c' : 
tup_data = ('영인', 
박재균님이 모두에게:  12:13 PM
1. pd.Series(dict_data)

2. pd.Series(list_data)

3. pd.Series(tup_data)

4. pd.Series(tup_data, index = index_name)
상우 박님이 모두에게:  12:14 PM
네
김병룡님이 모두에게:  12:14 PM
dict_data = {'a':1,'b':2,'c':3}
dict_data=pd.Series(dict_data)
print(dict_data.index)
print(dict_data.values)

list_data=['2019-01-02', 3.14, 'ABC', 100, True]
list_data=pd.Series(list_data)
print(list_data.index)
print(list_data.values)

tup_data=('영인','2010-05-01','여',True)
tup_data=pd.Series(tup_data)
print(tup_data.index)
print(tup_data.values)

tup_data=('영인','2010-05-01','여',True)
index_name=['이름', '생년월일', '성별', '학생여부']
pd.Series(tup_data, index=index_name)

dict_data = {'a' : 1, 'b' : 2, 'c' : 3}

data = pd.Series(dict_data)

index = data.index
index

values = data.values
values

tup_data = ('영인', '2010-05-01', '여', True)
index_name = ['이름', '생년월일', '성별', '학생여부']

data2 = pd.Series(tup_data, index=index_name)
data2

1. pd.Series(dict_data)

2. pd.Series(list_data)

3. pd.Series(tup_data)

4. pd.Series(tup_data, index = index_name)

dict_data = {'a':1,'b':2,'c':3}
dict_data=pd.Series(dict_data)
print(dict_data.index)
print(dict_data.values)

list_data=['2019-01-02', 3.14, 'ABC', 100, True]
list_data=pd.Series(list_data)
print(list_data.index)
print(list_data.values)

tup_data=('영인','2010-05-01','여',True)
tup_data=pd.Series(tup_data)
print(tup_data.index)
print(tup_data.values)

tup_data=('영인','2010-05-01','여',True)
index_name=['이름', '생년월일', '성별', '학생여부']
pd.Series(tup_data, index=index_name)

In [152]:
# 위는 4번까지의 정답모음

###### 5번정답, 6번정답

###### 7. 행인덱스 / 열이름 설정

In [153]:
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']],
                 index = ['준서', '예은'],
                 columns=['나이', '성별', '학교'])

df

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [ ]:
# 준서, 예은 -> '학생1', '학생2'

In [ ]:
# 나이, 성별, 학교 -> '연령', '남녀', '소속'

###### 8. 행인덱스 / 열이름 변경

In [154]:
df = pd.DataFrame([[15, '남', '덕영중'], [17, '여', '수리중']],
                 index = ['준서', '예은'],
                 columns=['나이', '성별', '학교'])

df

나이 성별   학교
준서  15  남  덕영중
예은  17  여  수리중

In [155]:
# rename을 사용하여 변경하기

In [156]:
# 컬럼의 일부만 바구고 싶을때

In [ ]:
df.rename(columns = {'':'','':'','':'','':''}) # 형태로 하고 갯수는 맞추지 않아도 됨 # index를 넣어줘도 됨

In [157]:
# 새로운 복사본을 생성하지 원본은 그대로임

In [158]:
# 원본까지 반영하고 싶으면 저 명령어 뒤에 ', inplace=True' 를 붙이면 됨

## 중요한 기능들

### 1. 재색인

In [159]:
objx = pd.Series([4,7,-5,3], index = ['d','b','a','c'])
objx

d    4
b    7
a   -5
c    3
dtype: int64

In [160]:
obj2x = objx.reindex(['a','b','c','d','e'])
obj2x

a   -5.0
b    7.0
c    3.0
d    4.0
e    NaN
dtype: float64

In [161]:
obj3x = pd.Series(['blue', 'purple', 'yellow'], index=[0,2,4])
obj3x

0      blue
2    purple
4    yellow
dtype: object

In [162]:
obj3x.reindex(range(6))

0      blue
1       NaN
2    purple
3       NaN
4    yellow
5       NaN
dtype: object

In [163]:
# 알아서 빈자리에 값을 인덱스로 넣고 NaN 처리까지 해줌

In [164]:
# NaN 으로 처리된 부분 일괄 변경

In [165]:
obj3x.reindex(range(6), method='ffill')

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: object

In [166]:
# 앞 인덱스의 value 값을 가져와 다음 인덱스에 넣어줌

In [167]:
#ffill은 forward fill임

In [168]:
np.arange(9).reshape((3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [169]:
frame = pd.DataFrame(np.arange(9).reshape((3, 3)),
                     index=['a', 'c', 'd'],
                     columns=['Ohio', 'Texas', 'California'])
frame

Ohio  Texas  California
a     0      1           2
c     3      4           5
d     6      7           8

In [171]:
frame2 = frame.reindex(['a','b','c','d'])
frame2

Ohio  Texas  California
a   0.0    1.0         2.0
b   NaN    NaN         NaN
c   3.0    4.0         5.0
d   6.0    7.0         8.0

In [172]:
states = ['Texas', 'Utah', 'California']
frame.reindex(columns=states)

Texas  Utah  California
a      1   NaN           2
c      4   NaN           5
d      7   NaN           8

In [ ]:
frame.loc[['a','b','c','d'], states]

### 2. 로우나 칼럼 삭제하기

In [175]:
obj = pd.Series(np.arange(5))
obj

0    0
1    1
2    2
3    3
4    4
dtype: int32

In [176]:
obj = pd.Series(np.arange(5), index = ['a','b','c','d','e'])
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [177]:
obj.drop('c')

a    0
b    1
d    3
e    4
dtype: int32

In [178]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [179]:
# 이것도 역시 inplace 옵션을 실행해야 원본이 삭제됨

In [180]:
obj.drop(['d','c'])

a    0
b    1
e    4
dtype: int32

In [182]:
data = pd.DataFrame(np.arange(16).reshape(4,4),
                    index = ['Ohio','Colorado','Utah','New York'],
                    columns = ['1','2','3','4'])

In [183]:
data

1   2   3   4
Ohio       0   1   2   3
Colorado   4   5   6   7
Utah       8   9  10  11
New York  12  13  14  15

In [184]:
data.drop(['Colorado'])

1   2   3   4
Ohio       0   1   2   3
Utah       8   9  10  11
New York  12  13  14  15

In [185]:
data.drop(['Colorado', 'Ohio'])

1   2   3   4
Utah       8   9  10  11
New York  12  13  14  15

In [186]:
# 행 삭제는 위 처럼 하면 됨

In [187]:
# drop 에 쉬프트 탭을 해보면 axis 값이 기본적으로 0으로 설정되어 있음

In [188]:
# 즉, 행이 기본이란 말임

In [189]:
# data.drop(['Colorado', 'Ohio']) = data.drop(['Colorado', 'Ohio'], axis=0)

In [190]:
data.drop('2', axis=1)

1   3   4
Ohio       0   2   3
Colorado   4   6   7
Utah       8  10  11
New York  12  14  15

In [191]:
data.drop(['2','4'], axis=1) # 또는 data.drop(['2','4'], axis='columns') 컬럼스 대신 index 를 넣을수도 있음

1   3
Ohio       0   2
Colorado   4   6
Utah       8  10
New York  12  14

In [192]:
# 컬럼스는 1이고 인덱스는 0임

In [193]:
obj

a    0
b    1
c    2
d    3
e    4
dtype: int32

In [196]:
obj.drop('c', inplace=True) # 일차원 배열이라 행을 지정할 필요는 없음. 왜? obj는 Series 이니까

In [197]:
obj

a    0
b    1
d    3
e    4
dtype: int32

In [198]:
# C 가 삭제되었음

* 축에대해서 연산을 할 때

In [200]:
# 일반적으로는 그 축을 따라서 연산하면 되지만,
# 삭제하는 경우에는 그 축을 삭제

In [ ]:
df.sum (axis = 1)
df.mean
df.min
df.max

### 3. 색인하기, 선택하기, 거르기

In [212]:
obj = pd.Series(np.arange(4.), index = ['a','b','c','d'])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [213]:
obj['b']

1.0

In [214]:
obj[1]

1.0

In [215]:
obj[2:4]

c    2.0
d    3.0
dtype: float64

In [216]:
obj[['b', 'a','d']]

b    1.0
a    0.0
d    3.0
dtype: float64

In [217]:
obj[[1, 3]]

b    1.0
d    3.0
dtype: float64

In [218]:
obj < 2

a     True
b     True
c    False
d    False
dtype: bool

In [219]:
obj[obj < 2]

a    0.0
b    1.0
dtype: float64

In [220]:
obj['b':'c']

b    1.0
c    2.0
dtype: float64

In [221]:
obj['b':'c'] = 5
obj

a    0.0
b    5.0
c    5.0
d    3.0
dtype: float64

In [222]:
data = pd.DataFrame(np.arange(16).reshape(4,4),
                    index = ['Ohio','Colorado','Utah','New York'],
                    columns =['one','two','three','four'])
data

one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [223]:
data['two']

Ohio         1
Colorado     5
Utah         9
New York    13
Name: two, dtype: int32

In [224]:
data[['three', 'one']]

three  one
Ohio          2    0
Colorado      6    4
Utah         10    8
New York     14   12

In [225]:
data['three'] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [226]:
data[data['three'] > 5]

one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [227]:
data < 5

one    two  three   four
Ohio       True   True   True   True
Colorado   True  False  False  False
Utah      False  False  False  False
New York  False  False  False  False

In [228]:
data[data < 5]

one  two  three  four
Ohio      0.0  1.0    2.0   3.0
Colorado  4.0  NaN    NaN   NaN
Utah      NaN  NaN    NaN   NaN
New York  NaN  NaN    NaN   NaN

In [229]:
data[data < 5] = 0
data

one  two  three  four
Ohio        0    0      0     0
Colorado    0    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

* loc, iloc 선택하기

In [230]:
data.loc['Colorado']

one      0
two      5
three    6
four     7
Name: Colorado, dtype: int32

In [231]:
data.loc['Colorado', ['two','three']]

two      5
three    6
Name: Colorado, dtype: int32

In [232]:
data.iloc[1, [1, 2]] # 마지막 대괄호 안은 열임

two      5
three    6
Name: Colorado, dtype: int32

In [233]:
data.iloc[2, [3,0,1]]

four    11
one      8
two      9
Name: Utah, dtype: int32

In [234]:
# iloc는 숫자로 색인하면됨. 인덱스 이니까 0부터 시작하고 i가 정수를 의미

In [235]:
data.loc['Utah']

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [236]:
data.iloc[2]

one       8
two       9
three    10
four     11
Name: Utah, dtype: int32

In [238]:
data.loc[:'Utah', 'two']

Ohio        0
Colorado    5
Utah        9
Name: two, dtype: int32

In [241]:
data.iloc[:, :3]

one  two  three
Ohio        0    0      0
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [242]:
data.iloc[:,:3][data.three > 5]

one  two  three
Colorado    0    5      6
Utah        8    9     10
New York   12   13     14

In [243]:
data.three > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [244]:
# 트루만 가져옴

### 4. 정수색인

In [245]:
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [247]:
ser[:1] # 시리즈에는 행과 열이 없으니까 이게 가능

0    0.0
dtype: float64

In [248]:
ser.loc[:1] # 라벨색인이라 1번재 까지 가능

0    0.0
1    1.0
dtype: float64

In [249]:
ser.iloc[:1] # 정수색인이라 0번째 까지 가능

0    0.0
dtype: float64

## 실습

In [250]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

###### 1번. 행삭제

In [252]:
# 서준 행 삭제

In [258]:
df.drop(['서준'])

수학  영어   음악  체육
우현  80  89   95  90
인아  70  95  100  90

In [259]:
# 서준 우현 행 삭제

In [261]:
df.drop(['서준', '우현']) # , axis =1 붙여도됨

수학  영어   음악  체육
인아  70  95  100  90

###### 2번. 열삭제

In [ ]:
# 수학 열 삭제

In [267]:
df.drop('수학', 1)

영어   음악   체육
서준  98   85  100
우현  89   95   90
인아  95  100   90

In [ ]:
# 수학 영어 열 삭제

In [268]:
df.drop(['수학', '영어'], 1)

음악   체육
서준   85  100
우현   95   90
인아  100   90

###### 3번. 행선택

In [254]:
# 서준 행 선택 (라벨색인, 정수색인, 두가지임)

In [269]:
df.loc['서준']

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [270]:
df.iloc[0]

수학     90
영어     98
음악     85
체육    100
Name: 서준, dtype: int64

In [253]:
# 서준 우현 행 선택 (라밸색인, 정수색인, 슬라이싱 세가지임)

In [271]:
df.loc[['서준','우현']]

수학  영어  음악   체육
서준  90  98  85  100
우현  80  89  95   90

In [ ]:
df.iloc

###### 4번. 열선택

In [ ]:
#

In [255]:
# 수학 열 선택

In [262]:
# 음악 체육 열 선택

>> 정답모음

###### 서준 행 삭제
df.drop('서준')

###### 서준, 우현 행 삭제
df.drop(['서준', '우현'])

###### 수학 열 삭제
df.drop('수학', axis=1)

###### 수학, 영어 열 삭제
df.drop(['수학', '영어'], axis=1)

###### 서준 행 선택(라벨 색인, 정수 색인)
df.loc['서준']
df.iloc[0]

###### 서준, 우현 행 선택(라벨 색인, 정수 색인, 슬라이싱)
df.loc[['서준', '우현']]
df.iloc[[0, 1]]
df[:2]


df.drop(['서준'])
df.drop(['서준', '우현'])
df.drop(columns=['수학'])
df. drop(['수학','영어'], axis = 1)
df.loc['서준']
df.iloc[0]
df.loc[['서준','우현']]
df.iloc[[0,1],:]
df.iloc[0:2,:]

exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df


df.drop('서준')

df.drop(['서준','우현'])

df.drop(['수학','영어'], axis=1)

df.loc['서준']

df.iloc[0]

df.loc[['서준','우현']]

df.iloc[[0,1]]

df.iloc[:2]

###### 열선택 정답

df.drop(['서준']) #서준행삭제
df.drop(['서준', '우현']) # 서준 우현 행삭제
df.drop(columns=['수학']) # 수학 열삭제
df. drop(['수학','영어'], axis = 1) # 수학 영어 열삭제
df.loc['서준'] # 서준 라벨색인
df.iloc[0] # 서준 정수색인
df.loc[['서준','우현']] # 라벨
df.iloc[[0,1],:] # 정수
df.iloc[0:2,:] # 슬라이싱
df['수학']# 수학 열선택
df[['음악','체육']]# 음악 체육 열선택


---------------------------------------------


df.drop(['서준'])
df.drop(['서준','우현'])

df.drop(["수학"], axis=1)
df.drop(["수학","영어"], axis=1)

df.loc["서준"]
df.iloc[0]

df.loc[["서준", "우현"]]
df.iloc[[0,1]]
df.iloc[:2]

df[["수학"]]
df[["음악","체육"]]


------------------------------------------------


# 수학 열 선택
df['수학']

# 음악, 체육 열 선택
df[['음악', '체육']]



--------------------------------------------------


df[['수학']]

df[['음악','체육']]


In [263]:
# 대괄호 쓰는게 헤깔릴 수 있는데 대괄호를 1번쓰면 시리즈, 2번 쓰면 데이터프레임임
# 시리즈는 1차원, 데이터프레임은 2차원이기 때문임

###### 5번. 원소선택

In [264]:
# 서준의 음악점수

In [265]:
# 서준의 음악, 체육 점수

In [266]:
# 서준 우현의 음악, 체육 점수

###### 정답모음

df['수학']
df[['음악', '체육']]
df.loc[:]['수학']
df.loc[:][['음악', '체육']]
df.loc['서준']['음악']
df.loc['서준'][['음악', '체육']]
df.loc[['서준','우현']][['음악', '체육']]

--------------------------------------------

df.loc[['서준']][['음악']]

df.loc[['서준']][['음악','체육']]

df.loc[['서준','우현']][['음악','체육']]

--------------------------------------------

서준의 음악점수
df.iloc[0,2]
서준의 음악, 체육 점수
df.iloc[0,[2,3]]
서준 우현의 음악 체육 점수
df.iloc[0:2,2:4]

--------------------------------------------

서준의 음악 점수
df.loc['서준', '음악']

서준의 음악, 체육 점수
df.loc['서준', ['음악','체육']]

서준, 우현의 음악, 체육 점수
df.loc[['서준', '우현'], ['음악', '체육']]

#### 추가 실습 문제

* 같은 df를 이용해서 진행

In [272]:
exam_data = {'수학' : [ 90, 80, 70], '영어' : [ 98, 89, 95],
             '음악' : [ 85, 95, 100], '체육' : [ 100, 90, 90]}

df = pd.DataFrame(exam_data, index=['서준', '우현', '인아'])
df

수학  영어   음악   체육
서준  90  98   85  100
우현  80  89   95   90
인아  70  95  100   90

In [273]:
# 본인 이름으로 행 추가하기, 과목점수 임의로 지정

In [275]:
# 원소값 변경, 서준 체육 점수를 80점으로 변경하기(라벨색인, 정수색인)

In [276]:
# 서준의 음악, 체육 점수 변경 

In [277]:
# 행 열 바꾸기

In [278]:
df.T

서준  우현   인아
수학   90  80   70
영어   98  89   95
음악   85  95  100
체육  100  90   90

In [280]:
# reindex와 reset_index의 차이점

In [ ]:
df.reindex([]) # 없는애가 추가되면 NaN으로 표기해줌

In [279]:
# 특정 열을 인덱스로 설정하기 문제

exam_data = {'이름' : ['서준', '우현', '인아']
            }

## 5. 산술 연산과 데이터 정렬

In [281]:
s1 = pd.Series([7.3, -2.5, 3.4, 1.5], index=['a','c','d','e'])
s2 = pd.Series([-2.1,3.6,-1.5,4,3.1], index=['a','c','e','f','g'])

In [282]:
s1

a    7.3
c   -2.5
d    3.4
e    1.5
dtype: float64

In [283]:
s2

a   -2.1
c    3.6
e   -1.5
f    4.0
g    3.1
dtype: float64

In [284]:
s1 + s2

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [285]:
df1 = pd.DataFrame({'A' : [1,2]})
df2 = pd.DataFrame({'B' : [3,4]})

In [286]:
df1

A
0  1
1  2

In [287]:
df2

B
0  3
1  4

In [288]:
df1 + df2

A   B
0 NaN NaN
1 NaN NaN

In [289]:
df1-df2

A   B
0 NaN NaN
1 NaN NaN

In [290]:
# 키가 겹치는게 없느니까 계산 불가능

In [293]:
df1 = pd.DataFrame(np.arange(12).reshape(3,4), columns = list('abcd')) # ['a','b','c','d'] 랑 같음
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [295]:
df2 = pd.DataFrame(np.arange(20).reshape(4,5), columns = list('abcde'))
df2

a   b   c   d   e
0   0   1   2   3   4
1   5   6   7   8   9
2  10  11  12  13  14
3  15  16  17  18  19

In [296]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [297]:
df1 - df2

a    b    c    d   e
0  0.0  0.0  0.0  0.0 NaN
1 -1.0 -1.0 -1.0 -1.0 NaN
2 -2.0 -2.0 -2.0 -2.0 NaN
3  NaN  NaN  NaN  NaN NaN

In [298]:
# 채워 넣을 방법이 없어서 이렇게 나옴

In [299]:
df1.add(df2) # a.extend(b) 와 비슷

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0  11.0  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [300]:
# 결과는 동일하지만, 뒤의 add 라는 함수를 통해 여러 옵션을 추가할 수 있음

In [301]:
# 위는 메소드(방법)

df1.add(df2, fill_value = 0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0  11.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [302]:
# 없는 값을 0으로 바꿔서 계산해준거임

In [303]:
df1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [304]:
1 /  df1 # 쌉가능

a         b         c         d
0    inf  1.000000  0.500000  0.333333
1  0.250  0.200000  0.166667  0.142857
2  0.125  0.111111  0.100000  0.090909

In [305]:
df1.reindex(columns=df2.columns)

a  b   c   d   e
0  0  1   2   3 NaN
1  4  5   6   7 NaN
2  8  9  10  11 NaN

In [306]:
# 추가된 값이 없는 인덱스가 있지만, 큰 애의 인덱스로 재색인 해준거임

In [308]:
df1.reindex(columns=df2.columns, fill_value=0)

a  b   c   d  e
0  0  1   2   3  0
1  4  5   6   7  0
2  8  9  10  11  0

## 6. DataFrame 과 Series 간의 연산

In [310]:
arr = np.arange(12.).reshape((3,4))

In [311]:
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [312]:
# 어레이를 하나 준비했엉

In [313]:
arr[0]

array([0., 1., 2., 3.])

In [314]:
arr * 2

array([[ 0.,  2.,  4.,  6.],
       [ 8., 10., 12., 14.],
       [16., 18., 20., 22.]])

In [315]:
arr - arr[0]

array([[0., 0., 0., 0.],
       [4., 4., 4., 4.],
       [8., 8., 8., 8.]])

In [316]:
# 각 행에서 1234를 브로드캐스팅 해서 각각 빼줌

In [317]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                     columns = list('bde'),
                     index = ['Utah','Ohio','Texas','Oregon'])

series = frame.iloc[0]

In [318]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [319]:
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [320]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [321]:
# 쌉가능

In [322]:
series2 = pd.Series(range(3), index = ['b','e','f'])
series2

b    0
e    1
f    2
dtype: int64

In [323]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [324]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [325]:
# reshape() 형태로 기본적으로 괄호를 하나 써야하고, 안에 괄호 한 번 더 쓰고 3,4를 써야하는게 맞음
# 그런데 튜플처럼 그냥 3,4 를 해도 가능함

In [326]:
# BUT 넣는게 맞음

In [327]:
# 강의안과 다른부분이 있으니 강사님 py 파일 꼭 다시 볼 것

In [328]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [329]:
frame

b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [330]:
frame - series3

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [331]:
# 이런 연산은 안 씀

In [332]:
# series3 은 행단위가 아니라 d열로 색인해서 만든거라 열의 정보만 있음
# 프레임에서 시리즈를 뺄건데, 세로 방향으로 연산을 해야 짝이 맞음

frame.sub(series3, axis='index') # or 0

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [333]:
frame.sub(series3, axis=1) # 이렇게 하면 짝이 안맞아서 아래처럼 나옴

Ohio  Oregon  Texas  Utah   b   d   e
Utah     NaN     NaN    NaN   NaN NaN NaN NaN
Ohio     NaN     NaN    NaN   NaN NaN NaN NaN
Texas    NaN     NaN    NaN   NaN NaN NaN NaN
Oregon   NaN     NaN    NaN   NaN NaN NaN NaN

In [335]:
frametest = frame.T - series3 # 이러면 가능
frametest

Utah  Ohio  Texas  Oregon
b  -1.0  -1.0   -1.0    -1.0
d   0.0   0.0    0.0     0.0
e   1.0   1.0    1.0     1.0

In [336]:
frametest.T

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

# 실습

In [337]:
student1 = pd.Series({'국어':100, '영어':80, '수학':90})
student1

국어    100
영어     80
수학     90
dtype: int64

In [338]:
# 과목별 점수를 100으로 나눠보기

In [339]:
student1 / 100

국어    1.0
영어    0.8
수학    0.9
dtype: float64

In [340]:
student1.div(100)

국어    1.0
영어    0.8
수학    0.9
dtype: float64

In [341]:
student1 = pd.Series({'국어':100, '영어':80, '수학':90})
student2 = pd.Series({'수학':80, '국어':90, '영어':80})

In [342]:
# 두학생의 과목별 점수 평균

In [343]:
student1.add(student2).div(2)

국어    95.0
수학    85.0
영어    80.0
dtype: float64

In [344]:
(student1 + student2)/2

국어    95.0
수학    85.0
영어    80.0
dtype: float64

In [345]:
student1 = pd.Series({'국어':np.nan, '영어':80, '수학':90})
student2 = pd.Series({'수학':80, '국어':90})

In [346]:
# 두 학생의 평균

(student1 + student2)/2

국어     NaN
수학    85.0
영어     NaN
dtype: float64

In [347]:
# 서로 없는 과목에 대해서는 계산할 수 없음

In [348]:
student1.add(student2, fill_value=0).div(2)

국어    45.0
수학    85.0
영어    40.0
dtype: float64

In [349]:
# 없는 칸은 0으로 채워서 평균 구함

In [350]:
# 없는 값은 0더하고 2 나눈거니까, (그냥 한명값 + 0) / 2 한거임

In [351]:
# fillna 라는 문법으로 대응 가능